project_name: {{ProjectName}}

env:
  - GO111MODULE=on

before:
  hooks:
  - ./scripts/test.sh
  - ./scripts/report.sh

builds:
- main: ./cmd/{{ProjectName}}/main.go
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  binary: '{{"{{"}} .ProjectName {{"}}"}}'

archives:
- format: binary

dockers:
- binaries:
  - '{{"{{"}} .ProjectName {{"}}"}}'
  image_templates:
  - "{{Username}}/{{"{{"}}.ProjectName{{"}}"}}:latest"
  - "{{Username}}/{{"{{"}}.ProjectName{{"}}"}}:{{"{{"}} .Tag {{"}}"}}"
  - "{{Username}}/{{"{{"}}.ProjectName{{"}}"}}:v{{"{{"}} .Major {{"}}"}}"
  - "{{Username}}/{{"{{"}}.ProjectName{{"}}"}}:v{{"{{"}} .Major {{"}}"}}.{{"{{"}} .Minor {{"}}"}}"